### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by miraydamartinez** [iambritishdaniel/pwp-capstones#2]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code included runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Excellent use of python language features, both built-in and library extensions! Your use of the regular expressions (regex) library shows an in-depth understanding of the coding language. 

### Criteria 5: Produces Accurate Output
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code output is properly formatted and accurate. It was Lily Trebuchet! You found the killer :) 
 
### Overall Score: 20/20
Very great work! Your code was formatted properly which made it easy to follow along through each function. You also do a great job of (as stated above)  utilizing all of the features of the Python programming language. Though it would have been easier to just lower the text and then loop through the lowered text to prepare it -- in the prepare text function -- using the regex expressions was definitely impressive.

**Comment by iambritishdaniel** [comment]
Thanks for the feedback and quick review.
